### ISSUE TITLE
nodemon dev script error when installing package

### ISSUE THREAD

**Issue by Youssef-Dawoud** [mohammedelzanaty/m-zanaty-web-utils#3]
Hello,
I have an issue when I install the package I get an error message:
` Whoops!, Sir, Youssef... 😂💔 but Error: Command failed: npm set-script dev "nodemon ./src/index.ts"
    at checkExecSyncError (child_process.js:760:11)
    at execSync (child_process.js:833:15)
    at createIndexFile (C:\Users\Youssef\AppData\Roaming\npm\node_modules\m-zanaty-web-utils\build\modules\server-ts.module.js:24:40)
    at async createCombo (C:\Users\Youssef\AppData\Roaming\npm\node_modules\m-zanaty-web-utils\build\modules\node-ts-combo.module.js:16:5)
    at async run (C:\Users\Youssef\AppData\Roaming\npm\node_modules\m-zanaty-web-utils\build\index.js:23:13 )`

**Comment by moelzanaty3** [comment]
Hi thanks for raising an issue, I assume that the npm version that you have is less than 6 so could you please check and **Please, make sure u use npm version > v6.x**

**Comment by Youssef-Dawoud** [comment]
I have made sure my version is higher 6
